/* The following code was generated by JFlex 1.4.3 on 22/03/14 11:42 PM */

package parser_chat;
import java_cup.runtime.Symbol;

import java.util.LinkedList;



/**
 * This class is a scanner generated by 
 * <a href="http://www.jflex.de/">JFlex</a> 1.4.3
 * on 22/03/14 11:42 PM from the specification file
 * <tt>scanner.jflex</tt>
 */
public class scanner implements java_cup.runtime.Scanner {

  /** This character denotes the end of file */
  public static final int YYEOF = -1;

  /** initial size of the lookahead buffer */
  private static final int ZZ_BUFFERSIZE = 16384;

  /** lexical states */
  public static final int YYINITIAL = 0;

  /**
   * ZZ_LEXSTATE[l] is the state in the DFA for the lexical state l
   * ZZ_LEXSTATE[l+1] is the state in the DFA for the lexical state l
   *                  at the beginning of a line
   * l is of the form l = 2*k, k a non negative integer
   */
  private static final int ZZ_LEXSTATE[] = { 
     0, 0
  };

  /** 
   * Translates characters to character classes
   */
  private static final String ZZ_CMAP_PACKED = 
    "\11\0\1\53\1\53\1\0\2\53\22\0\1\53\1\0\1\25\3\22"+
    "\4\0\2\22\1\27\1\20\1\2\1\35\12\1\1\21\1\22\1\23"+
    "\1\26\1\24\1\22\1\5\1\15\1\50\1\42\1\46\1\44\1\51"+
    "\1\32\1\52\1\33\2\3\1\30\1\47\1\34\1\31\2\3\1\41"+
    "\1\37\1\45\1\36\1\43\4\3\4\0\1\4\1\0\1\40\1\50"+
    "\1\16\1\13\1\7\1\51\1\32\1\52\1\12\2\3\1\30\1\17"+
    "\1\34\1\14\2\3\1\10\1\6\1\45\1\36\1\11\4\3\65\0"+
    "\1\22\16\0\1\22\21\0\1\3\37\0\1\3\uff0e\0";

  /** 
   * Translates characters to character classes
   */
  private static final char [] ZZ_CMAP = zzUnpackCMap(ZZ_CMAP_PACKED);

  /** 
   * Translates DFA states to action switch labels.
   */
  private static final int [] ZZ_ACTION = zzUnpackAction();

  private static final String ZZ_ACTION_PACKED_0 =
    "\1\0\1\1\1\2\1\3\1\4\1\5\1\6\1\7"+
    "\1\10\1\11\1\12\2\2\2\0\1\4\11\0\1\2"+
    "\50\0\1\13\21\0\1\14\1\13\24\0\1\15\1\0"+
    "\1\16\1\17\12\0\1\20\1\14\1\0\1\21\1\22"+
    "\1\23\1\0\1\24\1\0\1\25\1\26\2\0\1\27"+
    "\2\0\1\30\1\31\1\32\2\0\1\33\2\0\1\34"+
    "\1\35\1\0\1\36\3\0\1\37";

  private static int [] zzUnpackAction() {
    int [] result = new int[152];
    int offset = 0;
    offset = zzUnpackAction(ZZ_ACTION_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAction(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /** 
   * Translates a state to a row index in the transition table
   */
  private static final int [] ZZ_ROWMAP = zzUnpackRowMap();

  private static final String ZZ_ROWMAP_PACKED_0 =
    "\0\0\0\54\0\130\0\54\0\204\0\260\0\54\0\54"+
    "\0\54\0\54\0\334\0\u0108\0\u0134\0\u0160\0\u018c\0\u01b8"+
    "\0\u01e4\0\u0210\0\u023c\0\u0268\0\u0294\0\u02c0\0\u02ec\0\u0318"+
    "\0\u0344\0\u0370\0\u039c\0\u03c8\0\u03f4\0\u0420\0\u044c\0\u0478"+
    "\0\u04a4\0\u04d0\0\u04fc\0\u0528\0\u0554\0\u0580\0\u05ac\0\u05d8"+
    "\0\u0604\0\u0630\0\u065c\0\u0688\0\u06b4\0\u06e0\0\u070c\0\u0738"+
    "\0\u0764\0\u0790\0\u07bc\0\u07e8\0\u0814\0\u0840\0\u086c\0\u0898"+
    "\0\u08c4\0\u08f0\0\u091c\0\u0948\0\u0974\0\u09a0\0\u09cc\0\u09f8"+
    "\0\u0a24\0\u0a50\0\u0a7c\0\u0aa8\0\u0ad4\0\u0b00\0\u0b2c\0\u0b58"+
    "\0\u0b84\0\u0bb0\0\u0bdc\0\u0c08\0\u0c34\0\u0c60\0\u0c8c\0\u0cb8"+
    "\0\u0ce4\0\u0d10\0\u0d3c\0\u0d68\0\u0d94\0\54\0\u0dc0\0\u0dec"+
    "\0\u0e18\0\u0e44\0\u0e70\0\u0e9c\0\u0ec8\0\u0ef4\0\u0f20\0\u0f4c"+
    "\0\u0f78\0\u0fa4\0\u0fd0\0\u0ffc\0\u1028\0\u1054\0\u1080\0\u10ac"+
    "\0\u10d8\0\u1104\0\54\0\u1130\0\54\0\54\0\u115c\0\u1188"+
    "\0\u11b4\0\u11e0\0\u120c\0\u1238\0\u1264\0\u1290\0\u12bc\0\u12e8"+
    "\0\54\0\54\0\u1314\0\54\0\54\0\54\0\u1340\0\54"+
    "\0\u136c\0\54\0\54\0\u1398\0\u13c4\0\54\0\u13f0\0\u141c"+
    "\0\54\0\54\0\54\0\u1448\0\u1474\0\54\0\u14a0\0\u14cc"+
    "\0\54\0\54\0\u14f8\0\54\0\u1524\0\u1550\0\u157c\0\54";

  private static int [] zzUnpackRowMap() {
    int [] result = new int[152];
    int offset = 0;
    offset = zzUnpackRowMap(ZZ_ROWMAP_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackRowMap(String packed, int offset, int [] result) {
    int i = 0;  /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int high = packed.charAt(i++) << 16;
      result[j++] = high | packed.charAt(i++);
    }
    return j;
  }

  /** 
   * The transition table of the DFA
   */
  private static final int [] ZZ_TRANS = zzUnpackTrans();

  private static final String ZZ_TRANS_PACKED_0 =
    "\1\2\1\3\1\4\1\5\2\2\12\5\3\4\1\6"+
    "\1\7\1\10\1\11\1\12\5\5\1\4\15\5\1\13"+
    "\55\0\1\14\1\15\15\0\1\16\1\17\33\0\1\20"+
    "\1\0\2\5\1\21\12\5\10\0\5\5\1\0\15\5"+
    "\10\0\1\22\2\0\1\23\3\0\1\24\11\0\1\25"+
    "\2\0\1\23\1\26\1\27\1\30\3\0\1\24\1\0"+
    "\1\22\4\0\1\31\55\0\1\13\1\0\1\32\1\15"+
    "\15\0\1\16\1\17\33\0\1\15\53\0\1\33\53\0"+
    "\1\34\53\0\1\20\3\5\1\21\12\5\10\0\5\5"+
    "\1\0\15\5\7\0\1\35\53\0\1\36\1\0\1\37"+
    "\26\0\1\36\1\0\1\37\46\0\1\40\47\0\1\41"+
    "\37\0\1\42\14\0\1\42\36\0\1\43\14\0\1\43"+
    "\31\0\1\44\2\0\1\45\3\0\1\46\11\0\1\47"+
    "\2\0\1\45\1\50\1\0\1\51\3\0\1\46\1\0"+
    "\1\44\4\0\1\52\10\0\1\53\30\0\1\53\23\0"+
    "\1\54\34\0\1\54\10\0\1\32\1\15\52\0\1\55"+
    "\16\0\1\56\34\0\1\57\17\0\1\60\41\0\1\61"+
    "\111\0\1\62\16\0\1\63\30\0\1\63\24\0\1\64"+
    "\20\0\1\64\35\0\1\65\22\0\1\65\45\0\1\66"+
    "\40\0\1\67\27\0\1\67\12\0\1\70\1\0\1\71"+
    "\26\0\1\70\1\0\1\71\46\0\1\72\47\0\1\73"+
    "\37\0\1\74\14\0\1\74\36\0\1\75\14\0\1\75"+
    "\30\0\1\76\30\0\1\76\23\0\1\77\34\0\1\77"+
    "\45\0\1\100\33\0\1\101\23\0\1\101\31\0\1\56"+
    "\34\0\1\102\73\0\1\60\33\0\1\103\62\0\1\104"+
    "\60\0\1\105\22\0\1\105\27\0\1\106\14\0\1\106"+
    "\40\0\1\107\23\0\1\107\22\0\1\110\31\0\1\110"+
    "\22\0\1\111\20\0\1\111\70\0\1\112\50\0\1\113"+
    "\16\0\1\114\30\0\1\114\24\0\1\115\20\0\1\115"+
    "\35\0\1\116\22\0\1\116\45\0\1\117\40\0\1\120"+
    "\27\0\1\120\42\0\1\121\33\0\1\122\23\0\1\122"+
    "\26\0\1\123\22\0\1\123\65\0\1\124\2\0\1\125"+
    "\53\0\1\126\63\0\1\127\55\0\1\130\32\0\1\130"+
    "\15\0\1\131\30\0\1\131\24\0\1\132\20\0\1\132"+
    "\27\0\1\133\34\0\1\133\43\0\1\134\27\0\1\135"+
    "\30\0\1\135\27\0\1\136\22\0\1\136\27\0\1\137"+
    "\14\0\1\137\40\0\1\140\23\0\1\140\22\0\1\141"+
    "\31\0\1\141\22\0\1\142\20\0\1\142\70\0\1\143"+
    "\20\0\1\144\22\0\1\144\65\0\1\145\11\0\1\146"+
    "\30\0\1\146\27\0\1\147\22\0\1\147\14\0\1\150"+
    "\64\0\1\151\55\0\1\152\14\0\1\152\46\0\1\153"+
    "\43\0\1\154\14\0\1\154\46\0\1\155\53\0\1\156"+
    "\36\0\1\157\34\0\1\157\22\0\1\160\32\0\1\160"+
    "\15\0\1\161\30\0\1\161\24\0\1\162\20\0\1\162"+
    "\27\0\1\163\34\0\1\163\43\0\1\164\27\0\1\165"+
    "\30\0\1\165\22\0\1\166\30\0\1\166\27\0\1\167"+
    "\22\0\1\167\25\0\1\170\20\0\1\170\44\0\1\171"+
    "\30\0\1\172\65\0\1\173\64\0\1\174\53\0\1\175"+
    "\53\0\1\176\43\0\1\177\14\0\1\177\46\0\1\200"+
    "\43\0\1\201\14\0\1\201\46\0\1\202\53\0\1\203"+
    "\36\0\1\204\34\0\1\204\21\0\1\205\20\0\1\205"+
    "\44\0\1\206\43\0\1\207\14\0\1\207\36\0\1\210"+
    "\63\0\1\211\53\0\1\212\53\0\1\213\43\0\1\214"+
    "\14\0\1\214\30\0\1\215\15\0\1\216\12\0\1\215"+
    "\24\0\1\217\51\0\1\220\15\0\1\221\12\0\1\220"+
    "\40\0\1\222\44\0\1\223\62\0\1\224\31\0\1\225"+
    "\67\0\1\226\51\0\1\227\56\0\1\230\34\0";

  private static int [] zzUnpackTrans() {
    int [] result = new int[5544];
    int offset = 0;
    offset = zzUnpackTrans(ZZ_TRANS_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackTrans(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      value--;
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /* error codes */
  private static final int ZZ_UNKNOWN_ERROR = 0;
  private static final int ZZ_NO_MATCH = 1;
  private static final int ZZ_PUSHBACK_2BIG = 2;

  /* error messages for the codes above */
  private static final String ZZ_ERROR_MSG[] = {
    "Unkown internal scanner error",
    "Error: could not match input",
    "Error: pushback value was too large"
  };

  /**
   * ZZ_ATTRIBUTE[aState] contains the attributes of state <code>aState</code>
   */
  private static final int [] ZZ_ATTRIBUTE = zzUnpackAttribute();

  private static final String ZZ_ATTRIBUTE_PACKED_0 =
    "\1\0\1\11\1\1\1\11\2\1\4\11\3\1\2\0"+
    "\1\1\11\0\1\1\50\0\1\1\21\0\1\1\1\11"+
    "\24\0\1\11\1\0\2\11\12\0\2\11\1\0\3\11"+
    "\1\0\1\11\1\0\2\11\2\0\1\11\2\0\3\11"+
    "\2\0\1\11\2\0\2\11\1\0\1\11\3\0\1\11";

  private static int [] zzUnpackAttribute() {
    int [] result = new int[152];
    int offset = 0;
    offset = zzUnpackAttribute(ZZ_ATTRIBUTE_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAttribute(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }

  /** the input device */
  private java.io.Reader zzReader;

  /** the current state of the DFA */
  private int zzState;

  /** the current lexical state */
  private int zzLexicalState = YYINITIAL;

  /** this buffer contains the current text to be matched and is
      the source of the yytext() string */
  private char zzBuffer[] = new char[ZZ_BUFFERSIZE];

  /** the textposition at the last accepting state */
  private int zzMarkedPos;

  /** the current text position in the buffer */
  private int zzCurrentPos;

  /** startRead marks the beginning of the yytext() string in the buffer */
  private int zzStartRead;

  /** endRead marks the last character in the buffer, that has been read
      from input */
  private int zzEndRead;

  /** number of newlines encountered up to the start of the matched text */
  private int yyline;

  /** the number of characters up to the start of the matched text */
  private int yychar;

  /**
   * the number of characters from the last newline up to the start of the 
   * matched text
   */
  private int yycolumn;

  /** 
   * zzAtBOL == true <=> the scanner is currently at the beginning of a line
   */
  private boolean zzAtBOL = true;

  /** zzAtEOF == true <=> the scanner is at the EOF */
  private boolean zzAtEOF;

  /** denotes if the user-EOF-code has already been executed */
  private boolean zzEOFDone;

  /* user code: */
/* Lista con errores sintacticos */
public LinkedList<Errores> lista=new LinkedList<Errores>();
/* Metodo que es llamado al encontrar un error lexico */
private void ErrorScan(int linea, int columna, String valor){
lista.add(new Errores(linea, columna, "Error lexico en el caracter "+valor) );}


  /**
   * Creates a new scanner
   * There is also a java.io.InputStream version of this constructor.
   *
   * @param   in  the java.io.Reader to read input from.
   */
  public scanner(java.io.Reader in) {
    this.zzReader = in;
  }

  /**
   * Creates a new scanner.
   * There is also java.io.Reader version of this constructor.
   *
   * @param   in  the java.io.Inputstream to read input from.
   */
  public scanner(java.io.InputStream in) {
    this(new java.io.InputStreamReader(in));
  }

  /** 
   * Unpacks the compressed character translation table.
   *
   * @param packed   the packed character translation table
   * @return         the unpacked character translation table
   */
  private static char [] zzUnpackCMap(String packed) {
    char [] map = new char[0x10000];
    int i = 0;  /* index in packed string  */
    int j = 0;  /* index in unpacked array */
    while (i < 156) {
      int  count = packed.charAt(i++);
      char value = packed.charAt(i++);
      do map[j++] = value; while (--count > 0);
    }
    return map;
  }


  /**
   * Refills the input buffer.
   *
   * @return      <code>false</code>, iff there was new input.
   * 
   * @exception   java.io.IOException  if any I/O-Error occurs
   */
  private boolean zzRefill() throws java.io.IOException {

    /* first: make room (if you can) */
    if (zzStartRead > 0) {
      System.arraycopy(zzBuffer, zzStartRead,
                       zzBuffer, 0,
                       zzEndRead-zzStartRead);

      /* translate stored positions */
      zzEndRead-= zzStartRead;
      zzCurrentPos-= zzStartRead;
      zzMarkedPos-= zzStartRead;
      zzStartRead = 0;
    }

    /* is the buffer big enough? */
    if (zzCurrentPos >= zzBuffer.length) {
      /* if not: blow it up */
      char newBuffer[] = new char[zzCurrentPos*2];
      System.arraycopy(zzBuffer, 0, newBuffer, 0, zzBuffer.length);
      zzBuffer = newBuffer;
    }

    /* finally: fill the buffer with new input */
    int numRead = zzReader.read(zzBuffer, zzEndRead,
                                            zzBuffer.length-zzEndRead);

    if (numRead > 0) {
      zzEndRead+= numRead;
      return false;
    }
    // unlikely but not impossible: read 0 characters, but not at end of stream    
    if (numRead == 0) {
      int c = zzReader.read();
      if (c == -1) {
        return true;
      } else {
        zzBuffer[zzEndRead++] = (char) c;
        return false;
      }     
    }

	// numRead < 0
    return true;
  }

    
  /**
   * Closes the input stream.
   */
  public final void yyclose() throws java.io.IOException {
    zzAtEOF = true;            /* indicate end of file */
    zzEndRead = zzStartRead;  /* invalidate buffer    */

    if (zzReader != null)
      zzReader.close();
  }


  /**
   * Resets the scanner to read from a new input stream.
   * Does not close the old reader.
   *
   * All internal variables are reset, the old input stream 
   * <b>cannot</b> be reused (internal buffer is discarded and lost).
   * Lexical state is set to <tt>ZZ_INITIAL</tt>.
   *
   * @param reader   the new input stream 
   */
  public final void yyreset(java.io.Reader reader) {
    zzReader = reader;
    zzAtBOL  = true;
    zzAtEOF  = false;
    zzEOFDone = false;
    zzEndRead = zzStartRead = 0;
    zzCurrentPos = zzMarkedPos = 0;
    yyline = yychar = yycolumn = 0;
    zzLexicalState = YYINITIAL;
  }


  /**
   * Returns the current lexical state.
   */
  public final int yystate() {
    return zzLexicalState;
  }


  /**
   * Enters a new lexical state
   *
   * @param newState the new lexical state
   */
  public final void yybegin(int newState) {
    zzLexicalState = newState;
  }


  /**
   * Returns the text matched by the current regular expression.
   */
  public final String yytext() {
    return new String( zzBuffer, zzStartRead, zzMarkedPos-zzStartRead );
  }


  /**
   * Returns the character at position <tt>pos</tt> from the 
   * matched text. 
   * 
   * It is equivalent to yytext().charAt(pos), but faster
   *
   * @param pos the position of the character to fetch. 
   *            A value from 0 to yylength()-1.
   *
   * @return the character at position pos
   */
  public final char yycharat(int pos) {
    return zzBuffer[zzStartRead+pos];
  }


  /**
   * Returns the length of the matched text region.
   */
  public final int yylength() {
    return zzMarkedPos-zzStartRead;
  }


  /**
   * Reports an error that occured while scanning.
   *
   * In a wellformed scanner (no or only correct usage of 
   * yypushback(int) and a match-all fallback rule) this method 
   * will only be called with things that "Can't Possibly Happen".
   * If this method is called, something is seriously wrong
   * (e.g. a JFlex bug producing a faulty scanner etc.).
   *
   * Usual syntax/scanner level error handling should be done
   * in error fallback rules.
   *
   * @param   errorCode  the code of the errormessage to display
   */
  private void zzScanError(int errorCode) {
    String message;
    try {
      message = ZZ_ERROR_MSG[errorCode];
    }
    catch (ArrayIndexOutOfBoundsException e) {
      message = ZZ_ERROR_MSG[ZZ_UNKNOWN_ERROR];
    }

    throw new Error(message);
  } 


  /**
   * Pushes the specified amount of characters back into the input stream.
   *
   * They will be read again by then next call of the scanning method
   *
   * @param number  the number of characters to be read again.
   *                This number must not be greater than yylength()!
   */
  public void yypushback(int number)  {
    if ( number > yylength() )
      zzScanError(ZZ_PUSHBACK_2BIG);

    zzMarkedPos -= number;
  }


  /**
   * Contains user EOF-code, which will be executed exactly once,
   * when the end of file is reached
   */
  private void zzDoEOF() throws java.io.IOException {
    if (!zzEOFDone) {
      zzEOFDone = true;
      yyclose();
    }
  }


  /**
   * Resumes scanning until the next regular expression is matched,
   * the end of input is encountered or an I/O-Error occurs.
   *
   * @return      the next token
   * @exception   java.io.IOException  if any I/O-Error occurs
   */
  public java_cup.runtime.Symbol next_token() throws java.io.IOException {
    int zzInput;
    int zzAction;

    // cached fields:
    int zzCurrentPosL;
    int zzMarkedPosL;
    int zzEndReadL = zzEndRead;
    char [] zzBufferL = zzBuffer;
    char [] zzCMapL = ZZ_CMAP;

    int [] zzTransL = ZZ_TRANS;
    int [] zzRowMapL = ZZ_ROWMAP;
    int [] zzAttrL = ZZ_ATTRIBUTE;

    while (true) {
      zzMarkedPosL = zzMarkedPos;

      yychar+= zzMarkedPosL-zzStartRead;

      boolean zzR = false;
      for (zzCurrentPosL = zzStartRead; zzCurrentPosL < zzMarkedPosL;
                                                             zzCurrentPosL++) {
        switch (zzBufferL[zzCurrentPosL]) {
        case '\u000B':
        case '\u000C':
        case '\u0085':
        case '\u2028':
        case '\u2029':
          yyline++;
          zzR = false;
          break;
        case '\r':
          yyline++;
          zzR = true;
          break;
        case '\n':
          if (zzR)
            zzR = false;
          else {
            yyline++;
          }
          break;
        default:
          zzR = false;
        }
      }

      if (zzR) {
        // peek one character ahead if it is \n (if we have counted one line too much)
        boolean zzPeek;
        if (zzMarkedPosL < zzEndReadL)
          zzPeek = zzBufferL[zzMarkedPosL] == '\n';
        else if (zzAtEOF)
          zzPeek = false;
        else {
          boolean eof = zzRefill();
          zzEndReadL = zzEndRead;
          zzMarkedPosL = zzMarkedPos;
          zzBufferL = zzBuffer;
          if (eof) 
            zzPeek = false;
          else 
            zzPeek = zzBufferL[zzMarkedPosL] == '\n';
        }
        if (zzPeek) yyline--;
      }
      zzAction = -1;

      zzCurrentPosL = zzCurrentPos = zzStartRead = zzMarkedPosL;
  
      zzState = ZZ_LEXSTATE[zzLexicalState];


      zzForAction: {
        while (true) {
    
          if (zzCurrentPosL < zzEndReadL)
            zzInput = zzBufferL[zzCurrentPosL++];
          else if (zzAtEOF) {
            zzInput = YYEOF;
            break zzForAction;
          }
          else {
            // store back cached positions
            zzCurrentPos  = zzCurrentPosL;
            zzMarkedPos   = zzMarkedPosL;
            boolean eof = zzRefill();
            // get translated positions and possibly new buffer
            zzCurrentPosL  = zzCurrentPos;
            zzMarkedPosL   = zzMarkedPos;
            zzBufferL      = zzBuffer;
            zzEndReadL     = zzEndRead;
            if (eof) {
              zzInput = YYEOF;
              break zzForAction;
            }
            else {
              zzInput = zzBufferL[zzCurrentPosL++];
            }
          }
          int zzNext = zzTransL[ zzRowMapL[zzState] + zzCMapL[zzInput] ];
          if (zzNext == -1) break zzForAction;
          zzState = zzNext;

          int zzAttributes = zzAttrL[zzState];
          if ( (zzAttributes & 1) == 1 ) {
            zzAction = zzState;
            zzMarkedPosL = zzCurrentPosL;
            if ( (zzAttributes & 8) == 8 ) break zzForAction;
          }

        }
      }

      // store back cached position
      zzMarkedPos = zzMarkedPosL;

      switch (zzAction < 0 ? zzAction : ZZ_ACTION[zzAction]) {
        case 23: 
          { return new Symbol(simbolo.fecha2, yychar,yyline,new String(yytext()));
          }
        case 32: break;
        case 21: 
          { return new Symbol(simbolo.clave2, yychar,yyline,new String(yytext()));
          }
        case 33: break;
        case 15: 
          { return new Symbol(simbolo.login1, yychar,yyline,new String(yytext()));
          }
        case 34: break;
        case 2: 
          { return new Symbol(simbolo.num, yychar,yyline,new String(yytext()));
          }
        case 35: break;
        case 13: 
          { return new Symbol(simbolo.error1, yychar,yyline,new String(yytext()));
          }
        case 36: break;
        case 8: 
          { return new Symbol(simbolo.igual, yychar,yyline,new String(yytext()));
          }
        case 37: break;
        case 7: 
          { return new Symbol(simbolo.c2, yychar,yyline,new String(yytext()));
          }
        case 38: break;
        case 30: 
          { return new Symbol(simbolo.usuarios2, yychar,yyline,new String(yytext()));
          }
        case 39: break;
        case 20: 
          { return new Symbol(simbolo.error2, yychar,yyline,new String(yytext()));
          }
        case 40: break;
        case 1: 
          { ErrorScan(yyline,yychar,yytext());
          }
        case 41: break;
        case 27: 
          { return new Symbol(simbolo.usuario1, yychar,yyline,new String(yytext()));
          }
        case 42: break;
        case 31: 
          { return new Symbol(simbolo.correo, yychar,yyline,new String(yytext()));
          }
        case 43: break;
        case 24: 
          { return new Symbol(simbolo.estado2, yychar,yyline,new String(yytext()));
          }
        case 44: break;
        case 6: 
          { return new Symbol(simbolo.cerrar, yychar,yyline,new String(yytext()));
          }
        case 45: break;
        case 11: 
          { return new Symbol(simbolo.hora, yychar,yyline,new String(yytext()));
          }
        case 46: break;
        case 10: 
          { /* Se ignoran */
          }
        case 47: break;
        case 25: 
          { return new Symbol(simbolo.inicio2, yychar,yyline,new String(yytext()));
          }
        case 48: break;
        case 19: 
          { return new Symbol(simbolo.nombre1, yychar,yyline,new String(yytext()));
          }
        case 49: break;
        case 22: 
          { return new Symbol(simbolo.login2, yychar,yyline,new String(yytext()));
          }
        case 50: break;
        case 9: 
          { return new Symbol(simbolo.coma, yychar,yyline,new String(yytext()));
          }
        case 51: break;
        case 29: 
          { return new Symbol(simbolo.usuarios1, yychar,yyline,new String(yytext()));
          }
        case 52: break;
        case 26: 
          { return new Symbol(simbolo.nombre2, yychar,yyline,new String(yytext()));
          }
        case 53: break;
        case 12: 
          { return new Symbol(simbolo.fecha, yychar,yyline,new String(yytext()));
          }
        case 54: break;
        case 3: 
          { return new Symbol(simbolo.signos, yychar,yyline,new String(yytext()));
          }
        case 55: break;
        case 4: 
          { return new Symbol(simbolo.cad, yychar,yyline,new String(yytext()));
          }
        case 56: break;
        case 17: 
          { return new Symbol(simbolo.estado1, yychar,yyline,new String(yytext()));
          }
        case 57: break;
        case 16: 
          { return new Symbol(simbolo.fecha1, yychar,yyline,new String(yytext()));
          }
        case 58: break;
        case 14: 
          { return new Symbol(simbolo.clave1, yychar,yyline,new String(yytext()));
          }
        case 59: break;
        case 28: 
          { return new Symbol(simbolo.usuario2, yychar,yyline,new String(yytext()));
          }
        case 60: break;
        case 5: 
          { return new Symbol(simbolo.abrir, yychar,yyline,new String(yytext()));
          }
        case 61: break;
        case 18: 
          { return new Symbol(simbolo.inicio1, yychar,yyline,new String(yytext()));
          }
        case 62: break;
        default: 
          if (zzInput == YYEOF && zzStartRead == zzCurrentPos) {
            zzAtEOF = true;
            zzDoEOF();
              { return new java_cup.runtime.Symbol(simbolo.EOF); }
          } 
          else {
            zzScanError(ZZ_NO_MATCH);
          }
      }
    }
  }


}
