
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Mon Mar 24 20:28:19 CST 2014
//----------------------------------------------------

package parser_chat;

/** CUP generated class containing symbol constants. */
public class simbolo {
  /* terminals */
  public static final int abrir = 11;
  public static final int inicio2 = 24;
  public static final int inicio1 = 23;
  public static final int correo_t = 10;
  public static final int login2 = 20;
  public static final int login1 = 19;
  public static final int fecha = 6;
  public static final int error2 = 26;
  public static final int solicitud2 = 40;
  public static final int error1 = 25;
  public static final int solicitud1 = 39;
  public static final int c2 = 5;
  public static final int usuario2 = 16;
  public static final int correo = 8;
  public static final int usuarios2 = 28;
  public static final int coma = 13;
  public static final int cerrar = 12;
  public static final int usuario1 = 15;
  public static final int usuarios1 = 27;
  public static final int clave2 = 18;
  public static final int igual = 14;
  public static final int clave1 = 17;
  public static final int nombre2 = 30;
  public static final int nombre1 = 29;
  public static final int respuesta2 = 48;
  public static final int respuesta1 = 47;
  public static final int estado2 = 22;
  public static final int estado1 = 21;
  public static final int emisor2 = 46;
  public static final int emisor1 = 45;
  public static final int fecha2 = 32;
  public static final int fecha1 = 31;
  public static final int contactos2 = 34;
  public static final int contactos1 = 33;
  public static final int EOF = 0;
  public static final int fecha_t = 9;
  public static final int error = 1;
  public static final int hora = 7;
  public static final int destinatario2 = 44;
  public static final int destinatario1 = 43;
  public static final int signos = 2;
  public static final int solicitudes2 = 38;
  public static final int solicitudes1 = 37;
  public static final int cad = 4;
  public static final int solicitudA2 = 42;
  public static final int contacto2 = 36;
  public static final int solicitudA1 = 41;
  public static final int contacto1 = 35;
  public static final int num = 3;
}

