/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package cliente;


import java.io.DataInputStream;
import java.io.DataOutputStream;
import java.io.IOException;
import java.net.Socket;
import java.net.UnknownHostException;
import java.util.Iterator;
import java.util.LinkedList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import parser.correo;
import parser.parser;
import server.*;

/**
 *
 * @author sebastian
 */
public class loginCorreo extends javax.swing.JFrame implements Runnable {

    // The client socket
   public Socket clientSocket = null;
    // The output stream
    public DataOutputStream os = null;
    // The input stream
   public DataInputStream is = null;
    public String responseLine = "";
public LinkedList<correo>  listaC;
    Thread t = null;
    server servidor = new server();
     cliente cliente = new cliente();
   //  clientThread ct = 
    /**
     * Creates new form loginCorreo
     */
    public loginCorreo() {
        initComponents();
         int portNumber = 2222;
        // The default host.
        String host = "localhost";
        try {
            clientSocket = new Socket(host, portNumber);
            os = new DataOutputStream(clientSocket.getOutputStream());
            is = new DataInputStream(clientSocket.getInputStream());
        } catch (UnknownHostException e) {
            System.err.println("Don't know about host " + host);
        } catch (IOException e) {
            System.err.println("Couldn't get I/O for the connection to the host "
                    + host);
        }

        t = new Thread(this);
        t.start();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        mainCorreo = new javax.swing.JFrame();
        jLabel5 = new javax.swing.JLabel();
        jScrollPane6 = new javax.swing.JScrollPane();
        listBandeja = new javax.swing.JList();
        jButton1 = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        txtAdjunto = new javax.swing.JTextArea();
        jScrollPane2 = new javax.swing.JScrollPane();
        txtContenido = new javax.swing.JTextArea();
        labelDestinatario = new javax.swing.JLabel();
        redactarCorreo = new javax.swing.JFrame();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtCorreo = new javax.swing.JTextArea();
        btnEnviar = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        txtUser = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        btnIniciarSesion = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        txtPass = new javax.swing.JPasswordField();

        mainCorreo.setMinimumSize(new java.awt.Dimension(792, 354));

        jLabel5.setText("Bandeja de Entrada");

        listBandeja.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                listBandejaMouseClicked(evt);
            }
        });
        jScrollPane6.setViewportView(listBandeja);

        jButton1.setText("Redactar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        txtAdjunto.setColumns(20);
        txtAdjunto.setRows(5);
        jScrollPane3.setViewportView(txtAdjunto);

        txtContenido.setColumns(20);
        txtContenido.setRows(5);
        jScrollPane2.setViewportView(txtContenido);

        labelDestinatario.setText("destinatario");

        javax.swing.GroupLayout mainCorreoLayout = new javax.swing.GroupLayout(mainCorreo.getContentPane());
        mainCorreo.getContentPane().setLayout(mainCorreoLayout);
        mainCorreoLayout.setHorizontalGroup(
            mainCorreoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, mainCorreoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(mainCorreoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(mainCorreoLayout.createSequentialGroup()
                        .addGroup(mainCorreoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButton1)
                            .addComponent(jLabel5))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jScrollPane6, javax.swing.GroupLayout.DEFAULT_SIZE, 425, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(mainCorreoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(labelDestinatario)
                    .addGroup(mainCorreoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 331, Short.MAX_VALUE)
                        .addComponent(jScrollPane3)))
                .addContainerGap())
        );
        mainCorreoLayout.setVerticalGroup(
            mainCorreoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(mainCorreoLayout.createSequentialGroup()
                .addGap(9, 9, 9)
                .addGroup(mainCorreoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(labelDestinatario))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(mainCorreoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(mainCorreoLayout.createSequentialGroup()
                        .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, 249, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton1)
                        .addContainerGap())
                    .addGroup(mainCorreoLayout.createSequentialGroup()
                        .addComponent(jScrollPane2)
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(24, 24, 24))))
        );

        redactarCorreo.setMinimumSize(new java.awt.Dimension(597, 395));

        txtCorreo.setColumns(20);
        txtCorreo.setRows(5);
        txtCorreo.setMinimumSize(new java.awt.Dimension(260, 95));
        jScrollPane1.setViewportView(txtCorreo);

        btnEnviar.setText("Enviar");
        btnEnviar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEnviarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout redactarCorreoLayout = new javax.swing.GroupLayout(redactarCorreo.getContentPane());
        redactarCorreo.getContentPane().setLayout(redactarCorreoLayout);
        redactarCorreoLayout.setHorizontalGroup(
            redactarCorreoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(redactarCorreoLayout.createSequentialGroup()
                .addGroup(redactarCorreoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(redactarCorreoLayout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 551, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(redactarCorreoLayout.createSequentialGroup()
                        .addGap(236, 236, 236)
                        .addComponent(btnEnviar)))
                .addContainerGap(25, Short.MAX_VALUE))
        );
        redactarCorreoLayout.setVerticalGroup(
            redactarCorreoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(redactarCorreoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 314, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnEnviar)
                .addContainerGap(28, Short.MAX_VALUE))
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Usuario:");

        txtUser.setText("Usuario1@servidorA.com");

        jLabel2.setText("Correo:");

        btnIniciarSesion.setText("Iniciar Sesion");
        btnIniciarSesion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIniciarSesionActionPerformed(evt);
            }
        });

        jLabel3.setForeground(java.awt.Color.blue);
        jLabel3.setText("Crear Cuenta");
        jLabel3.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel3MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(73, 73, 73)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2))
                .addGap(37, 37, 37)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnIniciarSesion, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addComponent(jLabel3))
                    .addComponent(txtUser, javax.swing.GroupLayout.DEFAULT_SIZE, 223, Short.MAX_VALUE)
                    .addComponent(txtPass))
                .addContainerGap(49, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(67, 67, 67)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtUser, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtPass, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(btnIniciarSesion)
                .addGap(27, 27, 27)
                .addComponent(jLabel3)
                .addContainerGap(62, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnIniciarSesionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIniciarSesionActionPerformed
        // TODO add your handling code here:
        login(txtUser.getText(), txtPass.getText());
    }//GEN-LAST:event_btnIniciarSesionActionPerformed

    private void jLabel3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel3MouseClicked
        // TODO add your handling code here:
        
        new crearCuenta().setVisible(true);
    }//GEN-LAST:event_jLabel3MouseClicked

    private void listBandejaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_listBandejaMouseClicked
        // TODO add your handling code here:
        //    System.out.println("click: "+listBandeja.getSelectedIndex());
        //    System.out.println("click: "+listBandeja.getSelectedValue().toString());
        int no;

        no = listBandeja.getSelectedIndex();

   //     System.out.println("click"+listaM.get(no-1).correo_d);
        String content = "<sesion id=\"correo\" peticion=\"correo\" de=\""+listaC.get(no-1).de+"\" fecha=\""+listaC.get(no-1).fecha +"\">\n" +
        "<usuario>"+listaC.get(no-1).usuario+"</usuario>\n" +
        "</sesion>";
        System.err.println("content: "+content);
        writeUTF(content);
    }//GEN-LAST:event_listBandejaMouseClicked

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
//writeUTF(txtContenido.getText());
//txtAdjunto.append(txtContenido.getText()+"\n");
redactarCorreo.setVisible(true);
redactarCorreo.setTitle("Redactar "+txtUser.getText());

    }//GEN-LAST:event_jButton1ActionPerformed

    private void btnEnviarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEnviarActionPerformed
        // TODO add your handling code here:
           writeUTF(txtCorreo.getText());
           
    }//GEN-LAST:event_btnEnviarActionPerformed

    public void crearCuenta(String contentCuenta){
        
        System.out.println("Cuenta: "+contentCuenta);
    }
    
    public void writeUTF(String content){
    try {
            os.writeUTF(content);
        } catch (IOException ex) {
            Logger.getLogger(Login2.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    
    public void login(String user, String pass){
    
        String xmlLogin = "<sesion id=\"correo\" tipo=\"inicio\">" +
                          "<Usuario>"+user+"</usuario>" +
                          "<clave>"+pass+"</clave>" +
                          "</sesion>";
        
     //  String msj;
       
        writeUTF(xmlLogin);
       //msj = servidor.iniciarSesion(xmlLogin);
       
      // msj = cliente.procesarMsjCuenta(msj);
      
     //  JOptionPane.showMessageDialog(null,msj, "Inicio Sesion",JOptionPane.INFORMATION_MESSAGE);
       
      // if (msj.contains("iniciada"))
           // new correo(user).setVisible(true);
    //   System.out.println(respuesta);
        //System.out.println("xmlLogin: "+xmlLogin);
        
     }
    
    public void compilar(String content){
    
       parser parser = cliente.compilar(content);
     
       
       switch (parser.respuesta){
       
           case 0:
               JOptionPane.showMessageDialog(null, "error parser", "Error",JOptionPane.INFORMATION_MESSAGE);
              txtAdjunto.append(content+"\n");
               break;
           case 1:
               JOptionPane.showMessageDialog(null, parser.msjCuenta, "Inicio Sesion",JOptionPane.INFORMATION_MESSAGE);
              jLabel3.setText("uno"+t.getName());
               break;
           case 2:
               JOptionPane.showMessageDialog(null, parser.msjCuenta, "Inicio Sesion",JOptionPane.INFORMATION_MESSAGE);
               
               this.setVisible(false);
               mainCorreo.setVisible(true);
             //  jLabel3.setText("dos"+t.getName());
               mainCorreo.setTitle(txtUser.getText());
               String peticion = "<sesion id=\"correo\" peticion=\"Lista correos\">\n"+
                                "<usuario>"+txtUser.getText()+"</usuario>\n"+
                                "</sesion>";
               writeUTF(peticion);
               break;
           case 4:
            listaC = parser.listaCorreos;
         //System.out.println("####CORREOS ----");

            Iterator<correo> itM = listaC.iterator(); /*
             * Listar los errores que se han guardado en la variable lista
             */
            String[] correos = new String[1000];
            int c =0;
            while (itM.hasNext()) {
                c++;
                correo correo = itM.next();
               // System.out.println("nombre: " + listaM.getNombre_d() + " asunto :" + listaM.getAsunto() + " de: " + listaM.getEmisor());
              // txtBandeja.append(listaM.getNombre_d()+"-"+listaM.getAsunto()+"-"+listaM.getFecha()+"\n");
             correos[c]= correo.nombre_de+"-"+correo.asunto+"-"+correo.fecha;
               
            }
           
           //  listModel.addElement("uno");
           //  listModel.add(0, strings);
             listBandeja.setListData(correos);
               break;
           case 6:
               labelDestinatario.setText("Mensaje de "+parser.correo.nombre_de);
               txtContenido.setText(parser.correo.contenido);
               break;
           default:
               txtAdjunto.append(content+"\n");
               break;
               
       
       }
        
    
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(loginCorreo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(loginCorreo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(loginCorreo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(loginCorreo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new loginCorreo().setVisible(true);
            }
        });
    }
    
     public void run() {

     //responseLine;
        while (true) {
            try {
                responseLine = is.readUTF();
               // if (responseLine.contains("exito")) {
              //      System.err.println("exito");
               // }
                compilar(responseLine);
              //  mostrarMensaje(responseLine);
                System.out.println("response: "+responseLine);

            } catch (IOException e) {
                System.out.println("Could not read from server");
            }
            //jTextArea1.append(responseLine);

        }

    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnEnviar;
    private javax.swing.JButton btnIniciarSesion;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JLabel labelDestinatario;
    private javax.swing.JList listBandeja;
    private javax.swing.JFrame mainCorreo;
    private javax.swing.JFrame redactarCorreo;
    private javax.swing.JTextArea txtAdjunto;
    private javax.swing.JTextArea txtContenido;
    private javax.swing.JTextArea txtCorreo;
    private javax.swing.JPasswordField txtPass;
    private javax.swing.JTextField txtUser;
    // End of variables declaration//GEN-END:variables
}
