
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Thu Mar 27 22:54:34 CST 2014
//----------------------------------------------------

package parser_correo;

/** CUP generated class containing symbol constants. */
public class simbolo {
  /* terminals */
  public static final int abrir = 22;
  public static final int celda2 = 67;
  public static final int celda1 = 66;
  public static final int correo_t = 17;
  public static final int fecha = 6;
  public static final int registro2 = 39;
  public static final int registro1 = 38;
  public static final int error2 = 37;
  public static final int error1 = 36;
  public static final int c2 = 5;
  public static final int tamanio = 62;
  public static final int usuario2 = 29;
  public static final int correo = 20;
  public static final int usuarios2 = 15;
  public static final int coma = 24;
  public static final int cerrar = 23;
  public static final int usuario1 = 28;
  public static final int archivo2 = 61;
  public static final int correos2 = 48;
  public static final int usuarios1 = 14;
  public static final int clave2 = 31;
  public static final int igual = 25;
  public static final int archivo1 = 60;
  public static final int correos1 = 47;
  public static final int clave1 = 30;
  public static final int peticion = 40;
  public static final int nombre2 = 33;
  public static final int nombre1 = 32;
  public static final int inicio = 13;
  public static final int de = 42;
  public static final int lista = 43;
  public static final int pg = 57;
  public static final int listaC = 41;
  public static final int fecha2 = 35;
  public static final int envio = 8;
  public static final int fecha1 = 34;
  public static final int fila = 63;
  public static final int columna = 64;
  public static final int EOF = 0;
  public static final int fecha_t = 16;
  public static final int error = 1;
  public static final int color = 65;
  public static final int asunto2 = 52;
  public static final int contenido2 = 56;
  public static final int asunto1 = 51;
  public static final int contenido1 = 55;
  public static final int hora = 7;
  public static final int destinatario2 = 12;
  public static final int destinatario1 = 11;
  public static final int id = 18;
  public static final int correo2 = 50;
  public static final int correo1 = 49;
  public static final int signos = 2;
  public static final int tipo = 19;
  public static final int sesion2 = 27;
  public static final int sesion1 = 26;
  public static final int usuario = 46;
  public static final int cad = 4;
  public static final int enviado2 = 45;
  public static final int enviado1 = 44;
  public static final int de2 = 54;
  public static final int num = 3;
  public static final int de1 = 53;
  public static final int destinatarios2 = 10;
  public static final int archivos2 = 59;
  public static final int destinatarios1 = 9;
  public static final int archivos1 = 58;
  public static final int registro = 21;
}

