
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Wed Mar 19 22:56:28 CST 2014
//----------------------------------------------------

package parser;

/** CUP generated class containing symbol constants. */
public class simbolo {
  /* terminals */
  public static final int abrir = 17;
  public static final int correo_t = 12;
  public static final int fecha = 6;
  public static final int registro2 = 34;
  public static final int error2 = 32;
  public static final int registro1 = 33;
  public static final int error1 = 31;
  public static final int c2 = 5;
  public static final int usuario2 = 24;
  public static final int correo = 15;
  public static final int usuarios2 = 10;
  public static final int coma = 19;
  public static final int cerrar = 18;
  public static final int usuario1 = 23;
  public static final int archivo2 = 51;
  public static final int correos2 = 41;
  public static final int usuarios1 = 9;
  public static final int clave2 = 26;
  public static final int igual = 20;
  public static final int archivo1 = 50;
  public static final int correos1 = 40;
  public static final int clave1 = 25;
  public static final int peticion = 35;
  public static final int nombre2 = 28;
  public static final int nombre1 = 27;
  public static final int inicio = 8;
  public static final int de = 37;
  public static final int lista = 38;
  public static final int listaC = 36;
  public static final int fecha2 = 30;
  public static final int fecha1 = 29;
  public static final int EOF = 0;
  public static final int fecha_t = 11;
  public static final int error = 1;
  public static final int asunto2 = 45;
  public static final int contenido2 = 49;
  public static final int asunto1 = 44;
  public static final int contenido1 = 48;
  public static final int hora = 7;
  public static final int id = 13;
  public static final int correo2 = 43;
  public static final int correo1 = 42;
  public static final int signos = 2;
  public static final int tipo = 14;
  public static final int sesion2 = 22;
  public static final int sesion1 = 21;
  public static final int usuario = 39;
  public static final int cad = 4;
  public static final int de2 = 47;
  public static final int num = 3;
  public static final int de1 = 46;
  public static final int registro = 16;
}

